import type Database from "better-sqlite3";
import { DELIVERY_ERROR_CODES, type DeliveryErrorCode } from "@opentag/delivery-contract";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export { DELIVERY_ERROR_CODES } from "@opentag/delivery-contract";
export type { DeliveryErrorCode } from "@opentag/delivery-contract";

export const deliveryAttempts = sqliteTable("delivery_attempts", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull(), intentId: text("intent_id").notNull(), sequence: integer("sequence").notNull(), state: text("state").notNull(), revision: integer("revision").notNull(),
  causalId: text("causal_id").notNull(), operation: text("operation").notNull(), deliveryKind: text("delivery_kind").notNull(), presentationDigest: text("presentation_digest").notNull(), targetDigest: text("target_digest").notNull(),
  authorityKind: text("authority_kind").notNull(), evidencePolicy: text("evidence_policy").notNull(), provenanceKind: text("provenance_kind").notNull(), repositoryIdentityDigest: text("repository_identity_digest"), runId: text("run_id"), authorityLineageDigest: text("authority_lineage_digest"),
  inboundEventDigest: text("inbound_event_digest"), sourceThreadDigest: text("source_thread_digest"), provenanceInstallationId: text("provenance_installation_id"), provenanceRuntimeGeneration: integer("provenance_runtime_generation"), provenanceScopeId: text("provenance_scope_id"),
  providerPrincipalDigest: text("provider_principal_digest").notNull(), principalAssurance: text("principal_assurance").notNull(), connectionId: text("connection_id"), connectionIdDigest: text("connection_id_digest"), statusMessageId: text("status_message_id"), installationId: text("installation_id"), intentRuntimeGeneration: integer("intent_runtime_generation"),
  journalIntentDigest: text("journal_intent_digest").notNull(), authoritySnapshotDigest: text("authority_snapshot_digest").notNull(), scopeKind: text("scope_kind").notNull(), scopeId: text("scope_id").notNull(), idempotencyKey: text("idempotency_key").notNull(),
  providerId: text("provider_id").notNull(), providerInstanceId: text("provider_instance_id").notNull(), providerBindingDigest: text("provider_binding_digest").notNull(), providerConfigGeneration: integer("provider_config_generation").notNull(), providerConfigGenerationDigest: text("provider_config_generation_digest").notNull(),
  runtimeOwnerId: text("runtime_owner_id").notNull(), runtimeGeneration: integer("runtime_generation").notNull(), schemaGeneration: integer("schema_generation").notNull(), leaseOwner: text("lease_owner"), leaseExpiresAt: text("lease_expires_at"), leaseFenceDigest: text("lease_fence_digest"),
  installationBeginMarkerId: text("installation_begin_marker_id"), installationBeginMarkerDigest: text("installation_begin_marker_digest"), scopeBeginMarkerId: text("scope_begin_marker_id"), scopeBeginMarkerDigest: text("scope_begin_marker_digest"), begunAt: text("begun_at"), evidenceDigest: text("evidence_digest"), errorCode: text("error_code"),
  externalResourceDigest: text("external_resource_digest"), externalResourceId: text("external_resource_id"), outcomeRecordedAt: text("outcome_recorded_at"), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
}, (table) => ({
  intentIdx: uniqueIndex("delivery_attempts_intent_idx").on(table.intentId), digestIdx: uniqueIndex("delivery_attempts_journal_digest_idx").on(table.journalIntentDigest),
  idempotencyIdx: uniqueIndex("delivery_attempts_idempotency_idx").on(table.scopeKind, table.scopeId, table.providerId, table.providerInstanceId, table.idempotencyKey),
  claimIdx: index("delivery_attempts_claim_idx").on(table.state, table.leaseExpiresAt, table.createdAt, table.id),
}));

export function bootstrapDeliveryJournal(sqlite: Database.Database): void {
  const errors = DELIVERY_ERROR_CODES.map((code) => `'${code}'`).join(", ");
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS delivery_attempts (
      id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, intent_id TEXT NOT NULL UNIQUE, sequence INTEGER NOT NULL CHECK (sequence > 0), state TEXT NOT NULL CHECK (state IN ('pending', 'leased', 'provider_io_begun', 'accepted', 'rejected', 'outcome_unknown', 'attention')), revision INTEGER NOT NULL CHECK (revision > 0), causal_id TEXT NOT NULL, operation TEXT NOT NULL CHECK (operation IN ('create', 'update', 'control_reply')), delivery_kind TEXT NOT NULL CHECK (delivery_kind IN ('message', 'reaction')), presentation_digest TEXT NOT NULL, target_digest TEXT NOT NULL, authority_kind TEXT NOT NULL CHECK (authority_kind IN ('run_authority', 'hosted_send_authority', 'local_source_thread_control')), evidence_policy TEXT NOT NULL CHECK (evidence_policy IN ('local_audit', 'hosted_control')), provenance_kind TEXT NOT NULL CHECK (provenance_kind IN ('business', 'source_thread_control')), repository_identity_digest TEXT, run_id TEXT, authority_lineage_digest TEXT, inbound_event_digest TEXT, source_thread_digest TEXT, provenance_installation_id TEXT, provenance_runtime_generation INTEGER, provenance_scope_id TEXT, provider_principal_digest TEXT NOT NULL, principal_assurance TEXT NOT NULL CHECK (principal_assurance IN ('provider_verified', 'configured_declared')), connection_id TEXT, connection_id_digest TEXT, status_message_id TEXT, installation_id TEXT, intent_runtime_generation INTEGER, journal_intent_digest TEXT NOT NULL UNIQUE, authority_snapshot_digest TEXT NOT NULL, scope_kind TEXT NOT NULL, scope_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, provider_id TEXT NOT NULL, provider_instance_id TEXT NOT NULL, provider_binding_digest TEXT NOT NULL, provider_config_generation INTEGER NOT NULL CHECK (provider_config_generation > 0), provider_config_generation_digest TEXT NOT NULL, runtime_owner_id TEXT NOT NULL, runtime_generation INTEGER NOT NULL CHECK (runtime_generation > 0), schema_generation INTEGER NOT NULL CHECK (schema_generation > 0), lease_owner TEXT, lease_expires_at TEXT, lease_fence_digest TEXT, installation_begin_marker_id TEXT, installation_begin_marker_digest TEXT, scope_begin_marker_id TEXT, scope_begin_marker_digest TEXT, begun_at TEXT, evidence_digest TEXT, error_code TEXT CHECK (error_code IS NULL OR error_code IN (${errors})), external_resource_digest TEXT CHECK (external_resource_digest IS NULL OR (length(external_resource_digest) = 71 AND substr(external_resource_digest, 1, 7) = 'sha256:')), external_resource_id TEXT CHECK (external_resource_id IS NULL OR length(external_resource_id) BETWEEN 1 AND 512), outcome_recorded_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
      CHECK ((connection_id IS NULL AND connection_id_digest IS NULL) OR (connection_id IS NOT NULL AND connection_id_digest IS NOT NULL)),
      CHECK ((provenance_kind = 'business' AND repository_identity_digest IS NOT NULL AND run_id IS NOT NULL AND authority_lineage_digest IS NOT NULL AND inbound_event_digest IS NULL AND source_thread_digest IS NULL AND provenance_installation_id IS NULL AND provenance_runtime_generation IS NULL AND provenance_scope_id IS NULL AND installation_id IS NULL AND intent_runtime_generation IS NULL) OR (provenance_kind = 'source_thread_control' AND repository_identity_digest IS NULL AND run_id IS NULL AND authority_lineage_digest IS NULL AND inbound_event_digest IS NOT NULL AND source_thread_digest IS NOT NULL AND provenance_installation_id IS NOT NULL AND provenance_runtime_generation > 0 AND provenance_scope_id IS NOT NULL AND installation_id IS NOT NULL AND intent_runtime_generation > 0)),
      CHECK ((state = 'pending' AND lease_owner IS NULL AND lease_expires_at IS NULL AND lease_fence_digest IS NULL AND installation_begin_marker_id IS NULL AND installation_begin_marker_digest IS NULL AND scope_begin_marker_id IS NULL AND scope_begin_marker_digest IS NULL AND begun_at IS NULL AND evidence_digest IS NULL AND error_code IS NULL AND external_resource_digest IS NULL AND external_resource_id IS NULL AND outcome_recorded_at IS NULL) OR (state = 'leased' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND lease_fence_digest IS NOT NULL AND installation_begin_marker_id IS NULL AND installation_begin_marker_digest IS NULL AND scope_begin_marker_id IS NULL AND scope_begin_marker_digest IS NULL AND begun_at IS NULL AND evidence_digest IS NULL AND error_code IS NULL AND external_resource_digest IS NULL AND external_resource_id IS NULL AND outcome_recorded_at IS NULL) OR (state = 'provider_io_begun' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND lease_fence_digest IS NOT NULL AND installation_begin_marker_id IS NOT NULL AND installation_begin_marker_digest IS NOT NULL AND scope_begin_marker_id IS NOT NULL AND scope_begin_marker_digest IS NOT NULL AND begun_at IS NOT NULL AND evidence_digest IS NULL AND error_code IS NULL AND external_resource_digest IS NULL AND external_resource_id IS NULL AND outcome_recorded_at IS NULL) OR (state IN ('accepted', 'rejected', 'outcome_unknown', 'attention') AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND lease_fence_digest IS NOT NULL AND installation_begin_marker_id IS NOT NULL AND installation_begin_marker_digest IS NOT NULL AND scope_begin_marker_id IS NOT NULL AND scope_begin_marker_digest IS NOT NULL AND begun_at IS NOT NULL AND evidence_digest IS NOT NULL AND outcome_recorded_at IS NOT NULL AND ((state = 'accepted' AND error_code IS NULL) OR (state != 'accepted' AND error_code IS NOT NULL)) AND ((external_resource_digest IS NULL AND external_resource_id IS NULL) OR (state = 'accepted' AND external_resource_digest IS NOT NULL AND external_resource_id IS NOT NULL)))),
      UNIQUE (scope_kind, scope_id, provider_id, provider_instance_id, idempotency_key));
    CREATE INDEX IF NOT EXISTS delivery_attempts_claim_idx ON delivery_attempts(state, lease_expires_at, created_at, id);
    CREATE TRIGGER IF NOT EXISTS delivery_attempts_identity_immutable BEFORE UPDATE OF organization_id, intent_id, sequence, causal_id, operation, delivery_kind, presentation_digest, target_digest, authority_kind, evidence_policy, provenance_kind, repository_identity_digest, run_id, authority_lineage_digest, inbound_event_digest, source_thread_digest, provenance_installation_id, provenance_runtime_generation, provenance_scope_id, provider_principal_digest, principal_assurance, connection_id, connection_id_digest, status_message_id, installation_id, intent_runtime_generation, journal_intent_digest, authority_snapshot_digest, scope_kind, scope_id, idempotency_key, provider_id, provider_instance_id, provider_binding_digest, provider_config_generation, provider_config_generation_digest, runtime_owner_id, runtime_generation, schema_generation, created_at ON delivery_attempts BEGIN SELECT RAISE(ABORT, 'delivery_attempts identity is immutable'); END;
    CREATE TRIGGER IF NOT EXISTS delivery_attempts_transition_guard BEFORE UPDATE ON delivery_attempts WHEN NEW.revision != OLD.revision + 1 OR (OLD.state = 'pending' AND NEW.state != 'leased') OR (OLD.state = 'leased' AND NEW.state NOT IN ('pending', 'leased', 'provider_io_begun')) OR (OLD.state = 'provider_io_begun' AND NEW.state NOT IN ('accepted', 'rejected', 'outcome_unknown', 'attention')) OR OLD.state IN ('accepted', 'rejected', 'outcome_unknown', 'attention') OR (OLD.begun_at IS NOT NULL AND NEW.begun_at != OLD.begun_at) OR (OLD.installation_begin_marker_id IS NOT NULL AND NEW.installation_begin_marker_id != OLD.installation_begin_marker_id) OR (OLD.installation_begin_marker_digest IS NOT NULL AND NEW.installation_begin_marker_digest != OLD.installation_begin_marker_digest) OR (OLD.scope_begin_marker_id IS NOT NULL AND NEW.scope_begin_marker_id != OLD.scope_begin_marker_id) OR (OLD.scope_begin_marker_digest IS NOT NULL AND NEW.scope_begin_marker_digest != OLD.scope_begin_marker_digest) OR (OLD.evidence_digest IS NOT NULL AND NEW.evidence_digest != OLD.evidence_digest) OR (OLD.error_code IS NOT NULL AND NEW.error_code != OLD.error_code) OR (OLD.external_resource_digest IS NOT NULL AND NEW.external_resource_digest != OLD.external_resource_digest) OR (OLD.external_resource_id IS NOT NULL AND NEW.external_resource_id != OLD.external_resource_id) OR (OLD.outcome_recorded_at IS NOT NULL AND NEW.outcome_recorded_at != OLD.outcome_recorded_at) BEGIN SELECT RAISE(ABORT, 'invalid delivery_attempts transition'); END;
    CREATE TRIGGER IF NOT EXISTS delivery_attempts_immutable_delete BEFORE DELETE ON delivery_attempts BEGIN SELECT RAISE(ABORT, 'delivery_attempts are immutable'); END;
  `);
}
