import { zodToJsonSchema } from "zod-to-json-schema";
import {
  ActionHintSchema,
  AdapterMutationMappingSchema,
  ApplyIntentOutcomeSchema,
  ApplyPlanSchema,
  ApprovalDecisionSchema,
  ArtifactKindSchema,
  CapabilityContractSchema,
  CanonicalMutationDomainSchema,
  ContextPacketSchema,
  ConversationAnchorSchema,
  FollowUpRequestSchema,
  MutationIntentSchema,
  OpenTagEventSchema,
  OpenTagRunResultSchema,
  OpenTagRunSchema,
  ProposalLineageSchema,
  RunAdmissionDecisionSchema,
  RunArtifactTypeSchema,
  RunEventImportanceSchema,
  RunEventSchema,
  RunEventVisibilitySchema,
  PolicyResolutionSchema,
  SuggestedChangesSnapshotSchema,
  SuccessMetricNameSchema,
  WorkItemReferenceSchema,
  WorkThreadSchema
} from "./schema.js";
import {
  OpenTagExecutorProtocolEventSchema,
  OpenTagExecutorRunRequestSchema
} from "./executor-protocol.js";
import {
  OpenTagActorRefSchema,
  OpenTagChannelRefSchema,
  OpenTagChangeRequestRefSchema,
  OpenTagContextRefSchema,
  OpenTagIntegrationManifestSchema,
  OpenTagReplyTargetRefSchema,
  OpenTagRepoRefSchema,
  OpenTagRunSourceRefSchema,
  OpenTagRunTargetsSchema,
  OpenTagThreadRefSchema,
  OpenTagWorkItemRefSchema
} from "./integration-protocol.js";

export const OpenTagJsonSchemas = {
  OpenTagEvent: zodToJsonSchema(OpenTagEventSchema, "OpenTagEvent"),
  OpenTagRun: zodToJsonSchema(OpenTagRunSchema, "OpenTagRun"),
  OpenTagRunResult: zodToJsonSchema(OpenTagRunResultSchema, "OpenTagRunResult"),
  RunAdmissionDecision: zodToJsonSchema(RunAdmissionDecisionSchema, "RunAdmissionDecision"),
  FollowUpRequest: zodToJsonSchema(FollowUpRequestSchema, "FollowUpRequest"),
  WorkItemReference: zodToJsonSchema(WorkItemReferenceSchema, "WorkItemReference"),
  ConversationAnchor: zodToJsonSchema(ConversationAnchorSchema, "ConversationAnchor"),
  WorkThread: zodToJsonSchema(WorkThreadSchema, "WorkThread"),
  ContextPacket: zodToJsonSchema(ContextPacketSchema, "ContextPacket"),
  OpenTagIntegrationManifest: zodToJsonSchema(OpenTagIntegrationManifestSchema, "OpenTagIntegrationManifest"),
  OpenTagActorRef: zodToJsonSchema(OpenTagActorRefSchema, "OpenTagActorRef"),
  OpenTagChannelRef: zodToJsonSchema(OpenTagChannelRefSchema, "OpenTagChannelRef"),
  OpenTagThreadRef: zodToJsonSchema(OpenTagThreadRefSchema, "OpenTagThreadRef"),
  OpenTagRepoRef: zodToJsonSchema(OpenTagRepoRefSchema, "OpenTagRepoRef"),
  OpenTagChangeRequestRef: zodToJsonSchema(OpenTagChangeRequestRefSchema, "OpenTagChangeRequestRef"),
  OpenTagWorkItemRef: zodToJsonSchema(OpenTagWorkItemRefSchema, "OpenTagWorkItemRef"),
  OpenTagContextRef: zodToJsonSchema(OpenTagContextRefSchema, "OpenTagContextRef"),
  OpenTagRunSourceRef: zodToJsonSchema(OpenTagRunSourceRefSchema, "OpenTagRunSourceRef"),
  OpenTagRunTargets: zodToJsonSchema(OpenTagRunTargetsSchema, "OpenTagRunTargets"),
  OpenTagReplyTargetRef: zodToJsonSchema(OpenTagReplyTargetRefSchema, "OpenTagReplyTargetRef"),
  OpenTagExecutorRunRequest: zodToJsonSchema(OpenTagExecutorRunRequestSchema, "OpenTagExecutorRunRequest"),
  OpenTagExecutorProtocolEvent: zodToJsonSchema(OpenTagExecutorProtocolEventSchema, "OpenTagExecutorProtocolEvent"),
  RunEventVisibility: zodToJsonSchema(RunEventVisibilitySchema, "RunEventVisibility"),
  RunEventImportance: zodToJsonSchema(RunEventImportanceSchema, "RunEventImportance"),
  RunEvent: zodToJsonSchema(RunEventSchema, "RunEvent"),
  ArtifactKind: zodToJsonSchema(ArtifactKindSchema, "ArtifactKind"),
  RunArtifactType: zodToJsonSchema(RunArtifactTypeSchema, "RunArtifactType"),
  AdapterMutationMapping: zodToJsonSchema(AdapterMutationMappingSchema, "AdapterMutationMapping"),
  CapabilityContract: zodToJsonSchema(CapabilityContractSchema, "CapabilityContract"),
  PolicyResolution: zodToJsonSchema(PolicyResolutionSchema, "PolicyResolution"),
  ProposalLineage: zodToJsonSchema(ProposalLineageSchema, "ProposalLineage"),
  SuccessMetricName: zodToJsonSchema(SuccessMetricNameSchema, "SuccessMetricName"),
  ActionHint: zodToJsonSchema(ActionHintSchema, "ActionHint"),
  CanonicalMutationDomain: zodToJsonSchema(CanonicalMutationDomainSchema, "CanonicalMutationDomain"),
  MutationIntent: zodToJsonSchema(MutationIntentSchema, "MutationIntent"),
  SuggestedChangesSnapshot: zodToJsonSchema(SuggestedChangesSnapshotSchema, "SuggestedChangesSnapshot"),
  ApprovalDecision: zodToJsonSchema(ApprovalDecisionSchema, "ApprovalDecision"),
  ApplyPlan: zodToJsonSchema(ApplyPlanSchema, "ApplyPlan"),
  ApplyIntentOutcome: zodToJsonSchema(ApplyIntentOutcomeSchema, "ApplyIntentOutcome")
} as const;
