import { executorLabel } from "../catalogs/executors.js";
import { platformById } from "../catalogs/platforms.js";
import type { CliLanguage } from "../catalogs/languages.js";
import type { OpenTagCliConfig } from "../config.js";
import { githubLocalWebhookUrl, githubPublicWebhookUrlPlaceholder, githubWebhooksSettingsUrl } from "../platforms/github/display.js";
import { formatLarkPersonalAgentSummary } from "../platforms/lark/display.js";
import type { LarkSetupMethod, OpenTagSetupInput } from "./types.js";

function yesNo(value: boolean, language: CliLanguage): string {
  return language === "zh-CN" ? (value ? "是" : "否") : value ? "yes" : "no";
}

function larkSetupDescription(method: LarkSetupMethod, language: CliLanguage): string {
  if (language === "zh-CN") {
    if (method === "saved") return "使用已保存的 Personal Agent";
    return method === "scan" ? "创建新的 Personal Agent" : "手动填写";
  }
  if (method === "saved") return "Saved Personal Agent";
  return method === "scan" ? "Create new Personal Agent" : "Manual credentials";
}

export function formatSetupReview(input: OpenTagSetupInput, configPath: string): string {
  const platform = platformById(input.platform);
  const commonLines =
    input.language === "zh-CN"
      ? [
          "请确认 OpenTag 配置：",
          `配置文件: ${configPath}`,
          `平台: ${platform.label}`,
          `Coding agent: ${executorLabel(input.executor)}`,
          `项目路径: ${input.projectPath}`
        ]
      : [
          "Review your OpenTag setup:",
          `Config: ${configPath}`,
          `Platform: ${platform.label}`,
          `Coding agent: ${executorLabel(input.executor)}`,
          `Project path: ${input.projectPath}`
        ];

  const platformLines: string[] = [];
  if (input.lark) {
    const larkPersonalAgent = formatLarkPersonalAgentSummary(
      {
        ...input.lark,
        ...(input.lark.savedCredentialsSource ? { source: input.lark.savedCredentialsSource } : {})
      },
      input.language
    );
    platformLines.push(
      ...(input.language === "zh-CN"
        ? [
            `Lark 连接方式: ${larkSetupDescription(input.lark.setupMethod, input.language)}`,
            `Personal Agent: ${larkPersonalAgent}`,
            `Lark 域名: ${input.lark.domain}`,
            `默认绑定当前项目: ${yesNo(input.lark.bindingMethod === "default_project", input.language)}`
          ]
        : [
            `Lark setup: ${larkSetupDescription(input.lark.setupMethod, input.language)}`,
            `Personal Agent: ${larkPersonalAgent}`,
            `Lark domain: ${input.lark.domain}`,
            `Default project binding: ${yesNo(input.lark.bindingMethod === "default_project", input.language)}`
          ])
    );
  }
  if (input.slack) {
    const slackConnectionLines =
      input.slack.mode === "socket_mode"
        ? input.language === "zh-CN"
          ? ["Slack 连接方式: 本地 Socket Mode", "Slack 入站: 通过 Slack WebSocket，不需要公网 URL"]
          : ["Slack connection: Local Socket Mode", "Slack ingress: Slack WebSocket; no public URL required"]
        : input.language === "zh-CN"
          ? ["Slack 连接方式: 公网 Events API", `Slack Events URL: http://localhost:${input.slack.port ?? 3040}/slack/events`]
          : ["Slack connection: Public Events API", `Slack Events URL: http://localhost:${input.slack.port ?? 3040}/slack/events`];
    platformLines.push(
      ...(input.language === "zh-CN"
        ? [
            ...slackConnectionLines,
            `Slack Team ID: ${input.slack.teamId}`,
            `Slack Channel ID: ${input.slack.channelId}`,
            `默认绑定当前项目: ${yesNo(input.slack.bindingMethod === "default_project", input.language)}`
          ]
        : [
            ...slackConnectionLines,
            `Slack Team ID: ${input.slack.teamId}`,
            `Slack Channel ID: ${input.slack.channelId}`,
            `Default project binding: ${yesNo(input.slack.bindingMethod === "default_project", input.language)}`
          ])
    );
  }
  if (input.github) {
    const webhookPath = input.github.webhookPath;
    platformLines.push(
      ...(input.language === "zh-CN"
        ? [
            `GitHub 仓库: ${input.github.owner}/${input.github.repo}`,
            `GitHub 本地 webhook: ${githubLocalWebhookUrl({ port: input.github.port, webhookPath })}`,
            `GitHub Payload URL: ${githubPublicWebhookUrlPlaceholder(webhookPath)}`,
            "Webhook secret: OpenTag 会自动生成",
            `自动创建 pull request: ${yesNo(input.github.autoCreatePullRequest, input.language)}`
          ]
        : [
            `GitHub repository: ${input.github.owner}/${input.github.repo}`,
            `GitHub local webhook: ${githubLocalWebhookUrl({ port: input.github.port, webhookPath })}`,
            `GitHub Payload URL: ${githubPublicWebhookUrlPlaceholder(webhookPath)}`,
            "Webhook secret: generated by OpenTag",
            `Automatic pull requests: ${yesNo(input.github.autoCreatePullRequest, input.language)}`
          ])
    );
  }
  const lines = [...commonLines, ...platformLines];
  return lines.join("\n");
}

export function formatSetupComplete(config: OpenTagCliConfig, configPath: string): string {
  const repository = config.daemon.repositories[0];
  const language = config.preferences?.language ?? "en";
  const github = config.platforms.github;
  if (language === "zh-CN") {
    return [
      "OpenTag 配置已保存。",
      `配置文件: ${configPath}`,
      repository ? `项目路径: ${repository.checkoutPath}` : undefined,
      github ? "" : undefined,
      github ? "GitHub webhook 下一步：" : undefined,
      github ? `GitHub 设置页: ${githubWebhooksSettingsUrl(github)}` : undefined,
      github ? `Payload URL: ${githubPublicWebhookUrlPlaceholder(github.webhookPath ?? "/github/webhooks")}` : undefined,
      github ? `Secret: ${github.webhookSecret}` : undefined,
      github ? "Content type: application/json" : undefined,
      github ? "Events: Issue comments, Pull request review comments" : undefined,
      github ? `本地监听: ${githubLocalWebhookUrl({ port: github.port, webhookPath: github.webhookPath })}` : undefined,
      github ? "公网 URL 需要由 tunnel 指向本地监听地址，例如 ngrok http 3000。" : undefined
    ]
      .filter((line): line is string => Boolean(line))
      .join("\n");
  }
  return [
    "OpenTag config saved.",
    `Config: ${configPath}`,
    repository ? `Project path: ${repository.checkoutPath}` : undefined,
    github ? "" : undefined,
    github ? "GitHub webhook next steps:" : undefined,
    github ? `GitHub settings: ${githubWebhooksSettingsUrl(github)}` : undefined,
    github ? `Payload URL: ${githubPublicWebhookUrlPlaceholder(github.webhookPath ?? "/github/webhooks")}` : undefined,
    github ? `Secret: ${github.webhookSecret}` : undefined,
    github ? "Content type: application/json" : undefined,
    github ? "Events: Issue comments, Pull request review comments" : undefined,
    github ? `Local listener: ${githubLocalWebhookUrl({ port: github.port, webhookPath: github.webhookPath })}` : undefined,
    github ? "Point a public tunnel at the local listener, for example: ngrok http 3000." : undefined
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");
}
